@baseUrl = https://alaindube.com/api
@token = {{token}}

### 🩺 Health - Ping
GET {{baseUrl}}/ping
Accept: text/plain

##########################################################################################

### 👤 Auth - Register
POST {{baseUrl}}/auth/register
Content-Type: application/json

{
  "username": "username",
  "password": "Password123"
}


### 👤 Auth - Login
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "username": "username",
  "password": "Password123"
}

> {% client.global.set("token", response.headers["set-cookie"][0].split(";")[0].split("=")[1]) %}


### 👤 Auth - Me
GET {{baseUrl}}/auth/me
Cookie: token={{token}}


### 👤 Auth - Logout
POST {{baseUrl}}/auth/logout
Cookie: token={{token}}

###################################################################################################

### 🚢 Ships - Liste des navires
GET {{baseUrl}}/ships
Cookie: token={{token}}


### 🚢 Ships - Ajouter un navire
POST {{baseUrl}}/ships
Content-Type: application/json
Cookie: token={{token}}

{
  "name": "Black Pearl",
  "goldCargo": 500,
  "captain": "Jack Sparrow",
  "status": "sailing",
  "crewSize": 50
}


### 🚢 Ships - Supprimer tous les navires
DELETE {{baseUrl}}/ships
Cookie: token={{token}}


### 🚢 Ships - Obtenir un navire
GET {{baseUrl}}/ships/{{id}}
Cookie: token={{token}}


### 🚢 Ships - Mettre à jour un navire
PATCH {{baseUrl}}/ships/{{id}}
Content-Type: application/json
Cookie: token={{token}}

{
  "status": "docked"
}


### 🚢 Ships - Supprimer un navire
DELETE {{baseUrl}}/ships/{{id}}
Cookie: token={{token}}


### ⚓ Ships - Envoyer la liste d’utilisateurs du broker
GET {{baseUrl}}/ships/send/userlist
Cookie: token={{token}}


### ⚓ Ships - Envoyer un navire vers un autre port
POST {{baseUrl}}/ships/send/{{recipient}}
Content-Type: application/json
Cookie: token={{token}}

{
  "id": "fc7001d4-bc80-468f-9ca3-cbda91a3f605"
}


### ⚓ Ship - Dock (recevoir un navire)
POST {{baseUrl}}/ship/dock
Content-Type: application/json
Authorization: Bearer {{token}}
x-client-id: your-client-id

{
  "name": "Flying Dutchman",
  "goldCargo": 1000,
  "captain": "Davy Jones",
  "status": "sailing",
  "crewSize": 100,
  "createdBy": "william",
  "createdAt": "2025-09-30T16:02:09.305Z"
}
